source $HOME/.config/nvim/plugins.vim
source $HOME/.config/nvim/settings.vim
source $HOME/.config/nvim/keybindings.vim
source $HOME/.config/nvim/themes/material.vim
source $HOME/.config/nvim/plugin-config/airline-config.vim
source $HOME/.config/nvim/plugin-config/coc.vim
source $HOME/.config/nvim/plugin-config/fzf.vim
source $HOME/.config/nvim/plugin-config/git-support.vim
source $HOME/.config/nvim/plugin-config/navigation.vim
source $HOME/.config/nvim/plugin-config/explorer.vim
